#!/usr/bin/env bash

set -euo pipefail

cd "$(dirname "$0")/.."

# Mark the necessary Go modules as private to avoid Go's proxy
export GOPRIVATE="${GOPRIVATE:+$GOPRIVATE,}github.com/matrices/cerca-go,github.com/stainless-sdks/cerca-go"

echo "==> Running Go build"
go build ./...
